spring:
  config:
    import: optional:file:.env[.properties] # .env 파일 불러오기

  application:
    name: backend

  profiles:
    default: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/${LOCAL_DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL}login/oauth2/code/{registrationId}"

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL}login/oauth2/code/{registrationId}"
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL}login/oauth2/code/{registrationId}"
            scope: profile_nickname, profile_image # (이메일 필요하면 account_email 추가)
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: Authorization-refresh

app:
  storage:
    base-dir: ./uploads

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    default-produces-media-type: application/json
  packages-to-scan: com.meamappacaelestis.backend

logging:
  level:
    org:
      hibernate:
        type: info

location:
  kakao:
    base-url: https://dapi.kakao.com
    key : ${KAKAO_APP_SECRET}
    coord2address-path: /v2/local/geo/coord2regioncode.json



device:
  samsung:
    map:
      # ---- S 시리즈 (S6 ~ S24) ----
      SM-G920: "Galaxy S6"
      SM-G925: "Galaxy S6 Edge"
      SM-G930: "Galaxy S7"
      SM-G935: "Galaxy S7 Edge"
      SM-G950: "Galaxy S8"
      SM-G955: "Galaxy S8+"
      SM-G960: "Galaxy S9"
      SM-G965: "Galaxy S9+"
      SM-G970: "Galaxy S10e"
      SM-G973: "Galaxy S10"
      SM-G975: "Galaxy S10+"
      SM-G977: "Galaxy S10 5G"
      SM-G981: "Galaxy S20"
      SM-G986: "Galaxy S20+"
      SM-G988: "Galaxy S20 Ultra"
      SM-G780: "Galaxy S20 FE"
      SM-G781: "Galaxy S20 FE (5G)"
      SM-G991: "Galaxy S21"
      SM-G996: "Galaxy S21+"
      SM-G998: "Galaxy S21 Ultra"
      SM-G990: "Galaxy S21 FE"
      SM-S901: "Galaxy S22"
      SM-S906: "Galaxy S22+"
      SM-S908: "Galaxy S22 Ultra"
      SM-S911: "Galaxy S23"
      SM-S916: "Galaxy S23+"
      SM-S918: "Galaxy S23 Ultra"
      SM-S711: "Galaxy S23 FE"
      SM-S921: "Galaxy S24"
      SM-S926: "Galaxy S24+"
      SM-S928: "Galaxy S24 Ultra"
      SM-S721: "Galaxy S24 FE"

      # ---- Note 시리즈 ----
      SM-N920: "Galaxy Note5"
      SM-N930: "Galaxy Note7"
      SM-N935: "Galaxy Note FE"
      SM-N950: "Galaxy Note8"
      SM-N960: "Galaxy Note9"
      SM-N970: "Galaxy Note10"
      SM-N975: "Galaxy Note10+"
      SM-N976: "Galaxy Note10+ 5G"
      SM-N980: "Galaxy Note20"
      SM-N981: "Galaxy Note20 (변형)"
      SM-N986: "Galaxy Note20 Ultra"

      # ---- Z (Fold/Flip) ----
      SM-F900: "Galaxy Fold"
      SM-F700: "Galaxy Z Flip"
      SM-F916: "Galaxy Z Fold2"
      SM-F711: "Galaxy Z Flip3"
      SM-F926: "Galaxy Z Fold3"
      SM-F721: "Galaxy Z Flip4"
      SM-F936: "Galaxy Z Fold4"
      SM-F731: "Galaxy Z Flip5"
      SM-F946: "Galaxy Z Fold5"
      # (최신/향후 모델은 필요 시 추가)

      # ---- A 시리즈 (주요) ----
      SM-A105: "Galaxy A10"
      SM-A205: "Galaxy A20"
      SM-A305: "Galaxy A30"
      SM-A315: "Galaxy A31"
      SM-A325: "Galaxy A32"
      SM-A326: "Galaxy A32 5G"
      SM-A336: "Galaxy A33 5G"
      SM-A346: "Galaxy A34 5G"
      SM-A356: "Galaxy A35 5G"
      SM-A405: "Galaxy A40"
      SM-A505: "Galaxy A50"
      SM-A507: "Galaxy A50s"
      SM-A515: "Galaxy A51"
      SM-A525: "Galaxy A52"
      SM-A528: "Galaxy A52s"
      SM-A536: "Galaxy A53 5G"
      SM-A546: "Galaxy A54 5G"
      SM-A556: "Galaxy A55 5G"
      SM-A705: "Galaxy A70"
      SM-A715: "Galaxy A71"
      SM-A725: "Galaxy A72"
      SM-A736: "Galaxy A73 5G"
      SM-A125: "Galaxy A12"
      SM-A135: "Galaxy A13"
      SM-A137: "Galaxy A13 5G"
      SM-A146: "Galaxy A14 5G"
      SM-A156: "Galaxy A15 5G"
      SM-A245: "Galaxy A24"
      SM-A256: "Galaxy A25 5G"

      # ---- M 시리즈 (주요) ----
      SM-M105: "Galaxy M10"
      SM-M205: "Galaxy M20"
      SM-M305: "Galaxy M30"
      SM-M315: "Galaxy M31"
      SM-M325: "Galaxy M32"
      SM-M326: "Galaxy M32 5G"
      SM-M336: "Galaxy M33 5G"
      SM-M346: "Galaxy M34 5G"
      SM-M515: "Galaxy M51"
      SM-M526: "Galaxy M52 5G"
      SM-M536: "Galaxy M53 5G"
      SM-M546: "Galaxy M54 5G"

      # ---- F 시리즈/기타 (일부 지역 라인) ----
      SM-F415: "Galaxy F41"
      SM-F426: "Galaxy F42 5G"
      SM-F526: "Galaxy F52 5G"
      SM-F736: "Galaxy F73 (지역)"